name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up PATH
      run: |
        echo "::add-path::${ANDROID_HOME}/build-tools/30.0.1"
        echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build mod jar
      run: |
        chmod +x ./gradlew
        ./gradlew tools:processSprites
        ./gradlew mw:deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.REPOSITORY_NAME }}
        path: mw/build/libs/mw.jar
